baseurl = "https://kaseymarkel.github.io"
DefaultContentLanguage = "en"
title = "Kasey Markel"
# Using theme as git submodule 
theme = "beautifulhugo"
publishDir = "docs"
# Or when using theme as hugo module
# theme = "github.com/halogenica/beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"

[Services]
  [Services.Disqus]
    # Shortname = "XXX"
  [Services.googleAnalytics]
    # id = "XXX"

[Params]
  homeTitle = "Kasey Markel" # Set a different text for the header on the home page
  subtitle = "Plant Biologist"
  mainSections = ["post","posts"]
  # logo = "img/avatar-icon.png" # Expecting square dimensions - disabled to remove avatar
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = true
  readingTime = false
  wordCount = false
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  cusdisID = "XXX" # Get your App id from cusdis.com
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
#  disclaimerText = "The opinions expressed herein are my own personal opinions and do not represent my employerâ€™s view in any way."

[[Params.bigimg]]
 src = "img/sunset.jpg"
 desc = ""
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Params.author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Kasey Markel"
  # email = "youremail@domain.com"
  github = "kaseymarkel"
  bandcamp = "https://savagecitizen.bandcamp.com"
  500px = "kaseymarkel"
  linkedin = "kasey-markel"
  googlescholar = "https://scholar.google.com/citations?user=yLxNBqcAAAAJ&hl=en&oi=ao"
  

[[menu.main]]
    name = "About me"
    url = ""
    weight = 1

[[menu.main]]
    name = "Academic career"
    url = "page/academia"
    weight = 2

[[menu.main]]
    name = "Recreation"
    url = "page/recreation"
    weight = 3

[[menu.main]]
    name = "CV"
    url = "page/CV"
    weight = 4

